### ISSUE TITLE
对Python版本有要求吗？

### ISSUE THREAD

**Issue by DearTanker** [Ricky-Hao/V2Ray.Stats#1]
```
[root@200301~]# pip install v2ray_stats
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting v2ray_stats
  Downloading V2ray.Stats-0.3.1.tar.gz (6.3 kB)
Collecting schedule
  Downloading schedule-0.6.0-py2.py3-none-any.whl (8.7 kB)
Collecting texttable
  Downloading texttable-1.6.2-py2.py3-none-any.whl (10 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 14.8 MB/s
Requirement already satisfied: six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil->v2ray_stats) (1.14.0)
Building wheels for collected packages: v2ray-stats
  Building wheel for v2ray-stats (setup.py) ... done
  Created wheel for v2ray-stats: filename=V2ray.Stats-0.3.1-py2-none-any.whl size=8856 sha256=9d0580400dc9fb9c395421a52ef959756bab035fc3bbeeef17137b77041653c3
  Stored in directory: /root/.cache/pip/wheels/d6/96/f5/089d32941c12d15119edfd6653d0aeac2a00467ea5e6b1fc54
Successfully built v2ray-stats
Installing collected packages: schedule, texttable, python-dateutil, v2ray-stats
Successfully installed python-dateutil-2.8.1 schedule-0.6.0 texttable-1.6.2 v2ray-stats
```
```
[root@200301~]# python -m v2ray_stats -s 127.0.0.1:2335
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib64/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib64/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib64/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/usr/lib/python2.7/site-packages/v2ray_stats/__main__.py", line 17
    def init_database(db: str):
                        ^
SyntaxError: invalid syntax
```

**Comment by Ricky-Hao** [comment]
用的是python3

**Comment by DearTanker** [comment]
非常感谢，试试看。

**Comment by DearTanker** [comment]
```
[root@200301~]# python3 -m v2ray_stats -s 127.0.0.1:2335
/usr/bin/python3: No module named v2ray_stats
```
这。。

**Comment by Ricky-Hao** [comment]
我怀疑你没装好，看看pip3 -V的路径和你python3的路径对不对

**Comment by DearTanker** [comment]
```
[root@200301~]# pip3 -V
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
[root@200301~]# python3 -V
Python 3.6.8
```
应该装好了吧，我是CentOS7，用yum安装的Python3，因为还有其他默认使用的Python2，所以没有直接把Python替换成3的。

**Comment by DearTanker** [comment]
知道问题了，要用pip3 install。

**Comment by DearTanker** [comment]
可以运行起来，但是好像查不出数据。

**Comment by Ricky-Hao** [comment]
需要时间的累积，首先是一个常驻的后台收集数据，然后才有数据

**Comment by DearTanker** [comment]
看到daemon这边有报错了。

```
[INFO][2020-03-08 02:26:49] [V2Ray.Stats][utils]: Running in background.
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/v2ray_stats/scheduler.py", line 11, in wrapper
    return job_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/v2ray_stats/collector.py", line 19, in collect_traffic_stats
    stats_list = v2ctl.query_stats(pattern=pattern, reset=reset)
  File "/usr/local/lib64/python3.6/site-packages/v2ray_stats/v2ctl.py", line 51, in query_stats
    output = self._call_api(method='StatsService.QueryStats', request=request)
  File "/usr/local/lib64/python3.6/site-packages/v2ray_stats/v2ctl.py", line 31, in _call_api
    stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'v2ctl': 'v2ctl'

```

v2ctl 这个东西肯定是有的。在/usr/bin/v2ray/下。

**Comment by Ricky-Hao** [comment]
你可能需要把路径加入环境变量里
